apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: acme-corp-secret
  namespace: acme-corp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: acme-corp-credentials
    creationPolicy: Owner
  data:
    - secretKey: db_name
      remoteRef:
        key: tenant-acme-corp-credentials
        property: db_name
    - secretKey: db_user
      remoteRef:
        key: tenant-acme-corp-credentials
        property: db_user
    - secretKey: db_password
      remoteRef:
        key: tenant-acme-corp-credentials
        property: db_password