apiVersion: v1
kind: ServiceAccount
metadata:
  name: acme-corp-sa
  namespace: acme-corp
  annotations:
    # Workload Identity — K8s SA ko GCP SA se connect karo
    iam.gke.io/gcp-service-account: tenant-acme-corp-sa@demo-project-123.iam.gserviceaccount.com